### ISSUE TITLE
Форма проводки/ выбор счета

### ISSUE THREAD

**Issue by KlimovaEU** [logos-test/happy#4]
1. Развернуть примечания по умолчанию
2.  При выборе счета в выпадающем списке выводить номер счета, наименование счета, остаток в валюте счета.
3. При выборе счета выводить только счета - листы(без потомков).
4. При выборе счета для второй и последующей операции выводить только счета с той же валютой или мульти.

**Comment by eprincev-egor** [comment]
1 ок
4 ок

**Comment by eprincev-egor** [comment]
3 ok

**Comment by KlimovaEU** [comment]
молодца!
