### ISSUE TITLE
дерево счетов/ указание родственных связей

### ISSUE THREAD

**Issue by KlimovaEU** [logos-test/happy#7]
При установлении родственных связей, проверять что у ребенка тот же тип счета и ликвидность.
Также если у родителя валюта НЕ мульти, делать проверку, что валюты родственников совпадают (счета родителя и счета- потомка).

**Comment by eprincev-egor** [comment]
все кроме мульти

**Comment by KlimovaEU** [comment]
да, родитель- мульти может иметь каких угодно детей
